import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from '@/components/MainHeader';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Next Events",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="bg-gray-100 min-h-lvh">
            <MainHeader/>
            <main className="p-6">
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
